import React from 'react';
import ProjectContent from '@/components/project-detail/ProjectContent';
import ProjectInfo from '@/components/project-detail/ProjectInfo';
import ProjectRelease from '@/components/project-detail/ProjectRelease';
import { Metadata } from 'next';
import { sendRequest } from '@/utils/api';
import ModalNextProject from '@/components/reuse/ModalNextProject';

export const metadata: Metadata = {
    title: "Project Detail",
    description: "Generated by create next app",
};

const ProjectDetailPage = async ({ params }: { params: { slug: string } }) => {

    const resProject = await sendRequest<IBackendRes<IProject>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URL}/api/v1/projects/${params.slug}`,
        method: "GET",
        nextOption: {
            next: { tags: ['projects'] }
        }
    })
    const resProjects = await sendRequest<IResultPaginate<IProject>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URL}/api/v1/projects`,
        method: "GET",
        queryParams: {
            page: 1,
            size: 3,
            sort: 'id,desc',
        },
        nextOption: {
            next: { tags: ['projects'] }
        }
    })
    const resAllProjects = await sendRequest<IResultPaginate<IProject>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URL}/api/v1/projects`,
        method: "GET",
        queryParams: {
            page: 1,
            size: 100,
            sort: 'id,desc',
        },
        nextOption: {
            next: { tags: ['projects'] }
        }
    })

    return (
        <div
            className='bg-white'
        >
            <div className='flex flex-col gap-20 pb-20'>
                <div className='grid grid-cols-1 md:grid-cols-3 md:gap-28 px-6'>
                    <div className='md:col-span-1'>
                        <ProjectInfo project={resProject.data!} />
                    </div>
                    <div className='md:col-span-2'>
                        <ProjectContent project={resProject.data!} />
                    </div>
                </div>
                <div>
                    <div className='grid grid-cols-1 md:grid-cols-3 md:gap-36 px-6'>
                        <div className='md:col-span-1'>
                        </div>
                        <div className='md:col-span-2 flex md:gap-6 flex-col md:flex-row md:items-end'>
                            <ModalNextProject project={resProject.data!} projects={resAllProjects.data?.result!} />
                            <div className='subtitle-3-regular md:py-3 pl-16 md:pl-0 text-[#666D74]'>
                                {resProject.data?.subTitle}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <ProjectRelease projects={resProjects.data?.result!} />
        </div>
    )
}

export default ProjectDetailPage;