import ContentProject from '@/components/projects/ContentProject';
import { sendRequest } from '@/utils/api';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
    title: "Project",
    description: "Generated by create next app",
};


const ProjectPage = async () => {

    const projectRes = await sendRequest<IResultPaginate<IProject>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URL}/api/v1/projects?page=1&size=10`,
        method: "GET",
        nextOption: {
            next: { tags: ['projects'], revalidate: 10 }
        }
    })

    return (
        <div className='md:pt-20 pt-7 pb-28 flex flex-col md:gap-28 gap-10 bg-white'>
            <div className='px-5 flex justify-between items-end'>
                <h1 className='md:block hidden headline-4 text-black 2xl:text-[6vw] 2xl:leading-[6vw]'>Selected projects <br /> 2022-2024</h1>
                <h1 className='title-2-medium md:hidden block text-black'>Selected projects <br /> 2022-2024</h1>
                <h3 className='md:block hidden body-2-regular'>(SCROLL)</h3>
            </div>
            {projectRes?.data?.result && <ContentProject projects={projectRes.data.result} />}
        </div>
    )
}

export default ProjectPage;